services:
  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_NUM_PARALLEL=4 
      - OLLAMA_MAX_LOADED_MODELS=1 
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - ai_net

  # App (Shared AI Service). Em Linux, se estiver buildando em arquitetura
  # diferente (ex.: ARM), pode ser necessário adicionar: platform: linux/amd64
  app:
    build: .
    container_name: shared-ai-app
    depends_on:
      - ollama
    environment:
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: llama3.2:3b
    ports:
      - "8004:8000"
    networks:
      - ai_net

networks:
  ai_net:
    driver: bridge
